new route,controller,working links, date display, ordered, no revert
viktorJMarton/book-my-house pull request #3
Opened 2023-02-07 16:24 UTC by viktorJMarton

generated new  controller, added route for houses with only show and index . working links to the houses, booking list is  ordered beneath house name. No  option to revert the order.

2023-02-09 13:06 UTC, viktorJMarton commented
Time spent:
20.02.08. 12:30-17:30 : 5 h.

2023-02-09 13:54 UTC, Gregurevic requested changes
Több helyen is vannak felesleges üres sorok, vagy space-ek, illetve bizonyos helyekről hiányzik egy-egy space. Légyszi ezeket nézd át alaposan. A szebb kód segíteni fog abban, ha módosítani kell később a munkán.

2023-02-09 13:54 UTC, Gregurevic commented on app/assets/stylesheets/houses.scss
> +// Place all the styles related to the houses controller here.
Légyszi ezt a fájlt töröljük ki. A jelenlegi formájában nem csinál semmit, csak nagyobb tőle a kód.

2023-02-09 13:54 UTC, Gregurevic commented on app/controllers/houses_controller.rb
> +    @bookings_list= @house.bookings.sort_by(&:day).reverse if params[:order]=="desc"
Ezt érdemes lehet egy kicst átírni. Sokkal jobb lenne, ha az `if` -nek lenne egy egyértelmű `else` ága, mert a jelenlegi formában hibára tudunk futni akkor, ha pl params-ban beküldöm, hogy `{ order: 'IV.  Béla }` . Tudsz olyat csinálni Rails-ben, hogy az értékadást kiemeled az if-else elé. pl.:
```ruby
változó = if feltétel
    'érték #1'
  else
    'érték #2'
  end

2023-02-09 13:54 UTC, Gregurevic commented on app/helpers/houses_helper.rb
> +module HousesHelper
Légyszi ezt a fájlt töröljük ki. A jelenlegi formájában nem csinál semmit, csak nagyobb tőle a kód. Valszeg scaffolding miatt maradt benne, akárcsak a houses stylesheet fájl.

2023-02-09 13:54 UTC, Gregurevic commented on app/views/bookings/_booking.html.erb
> +    <%= link_to booking.house.name, booking.house %>
Ilyenkor érdemes kiírni a path helper-t, különben nehéz visszafejteni, hogy ez az endpoint pontosan hol van használva.

2023-02-09 13:54 UTC, Gregurevic commented on app/controllers/houses_controller.rb
> +    @bookings_list= @house.bookings.sort_by(&:day).reverse if params[:order]=="desc"
A `sort_by` helyett jobb lenne `order` -t használni. Így ez a kifejezés ActiveRecord oldalon tudna maradni, és gyorsabb lenne. Az `order` rögtön az SQL query-ben rendezi sorba a rekordokat, amíg a `sort_by` megvárja az SQL query eredményét, és utána, már a memóriába betöltött objektumokat, rendezi sorrendbe.
Így is működikk, de szebb lenne AR oldalon maradni.

2023-02-09 13:54 UTC, Gregurevic commented on test/controllers/houses_controller_test.rb
> +require "test_helper"
Légyszi ezt a fájlt töröljük ki. A jelenlegi formájában nem csinál semmit, csak nagyobb tőle a kód. Valszeg scaffolding miatt maradt benne, akárcsak a houses stylesheet fájl.

2023-02-10 14:13 UTC, Gregurevic commented on app/controllers/houses_controller.rb
> +    @bookings_list= @house.bookings.sort_by(&:day).reverse if params[:order]=="desc"
Bocsi, ehhez van még egy kommentem. Itt is használjunk légyszi `order` -t a `sort_by` helyett.
Csaláshoz linkelek doksit: https://apidock.com/rails/v5.2.3/ActiveRecord/QueryMethods/reverse_order ;)

2023-02-10 15:30 UTC, Gregurevic requested changes

2023-02-10 15:30 UTC, Gregurevic commented on app/views/houses/show.html.erb
> +  <%= link_to "Change order", house_path(@house, :order=>"asc")%>
Itt is légyszi az új syntax-ot használd!
```ruby
order: 'stuff'
```

2023-02-10 15:30 UTC, Gregurevic commented on app/views/houses/show.html.erb
> +  <%= link_to "Change order", house_path(@house, :order=>"asc")%>
Illetve ezt tudjuk egy kicsit kompaktabban is írni:
```erb
<%= link_to "Neve", valami_path(@valami, order: params ? '#1' : '#2') %>
```

2023-02-13 09:38 UTC, Gregurevic approved these changes

2023-02-13 10:09 UTC, merged