added customizable pagination
viktorJMarton/book-my-house pull request #5
Opened 2023-02-09 13:29 UTC by viktorJMarton

Time Spent:
23.02.08.: 18:00-19:00 : 1 h.

2023-02-09 14:11 UTC, Gregurevic commented on app/controllers/bookings_controller.rb
> +    @bookings = Booking.paginate(page: params[:page], per_page: per_page)
Én igyekszem mindig kerülni, hogy egyszer használatos változóba szervezzek ki kódokat. Csak olyankor szoktam, ha segíti a kód megértését. A kérdőjel kettőspont operátort tudod kicsit kompaktabban is írni:
```ruby
változó.presence || 4
# ugyan azt csinálja, mint
változó.present? ? változó : 'érték'
```
És így elférne egy sorban a kifejezés.

2023-02-09 14:11 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +  </div>
A fájlok végén mindig szoktunk hagyni egy üres sort. ;)

2023-02-09 14:13 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +
Itt egy kicsit szétcsúszott a formázás. Légyszi nézd át, hogy azonos szinten legyenek egyazon blokk nyitó és csukó tag-jei.

2023-02-09 14:15 UTC, Gregurevic commented on Gemfile
> +gem "bootstrap-will_paginate", "1.0.0"
A gem verziókat nem szoktuk lefixálni a Gemfile-ban, csak olyankor ha valami explicit indok van rá, hogy egy adott verziót kell tartani. pl.: Rails gem verziót mindig explicit meg szoktuk adni, de egy `will_paginate` verzió elég, ha csak a lockfile-ban van benne.

2023-02-09 14:19 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +    <%= will_paginate :container => true %>
Csomószor fogsz találkozni Rails-es forrásokkal, akik olyan formában adnak meg hash-eket, mint ahogy fent is írtad.
```ruby
{ :kulcs => 'érték' }
```
Ez viszont teljesen egyenértékű az alábbival. (Ez az újabb és a preferált syntax.)
```ruby
{ kulcs: 'érték' }
```

2023-02-10 15:34 UTC, Gregurevic commented on app/controllers/bookings_controller.rb
> +    @bookings = Booking.paginate(page: params[:page], per_page: per_page)
Itt a `per_page` -et tök szépen megírtad, viszont az eredeti `@bookings = Booking.all.ordered` benne maradt a kódban.

2023-02-10 15:38 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +
Itt még látok egy dupla üres sort, illetve a `will_paginate` sora mintha mélyebb indent-tel kezdődne, mint amire szüksége van.

2023-02-10 15:44 UTC, Gregurevic requested changes

2023-02-10 15:44 UTC, Gregurevic commented on app/controllers/bookings_controller.rb
> +    @bookings = Booking.paginate(page: params[:page], per_page: params[:per_page].presence || 4)
Itt a per_page -et tök szépen megírtad, viszont az eredeti `@bookings = Booking.all.ordered` benne maradt a kódban.

2023-02-10 15:44 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +<div class="pagination-options">
Itt még látok egy dupla üres sort.

2023-02-10 15:44 UTC, Gregurevic commented on app/views/bookings/index.html.erb
> +    <%= will_paginate container: true %>
A `will_paginate` sora mintha mélyebb indent-tel kezdődne, mint amire szüksége van.

2023-02-10 16:10 UTC, viktorJMarton commented on app/controllers/bookings_controller.rb
> +    @bookings = Booking.paginate(page: params[:page], per_page: params[:per_page].presence || 4)
Ez a 3-pagination branch en javítva van,   nem tudom milyen probléma  történt, hogy itt nem jelzi.

2023-02-13 09:42 UTC, Gregurevic approved these changes

2023-02-13 10:31 UTC, merged